# Generated by Django 2.0.3 on 2018-04-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180412_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatLog',
        ),
    ]
